### ISSUE TITLE
Two sound machines went offline

### ISSUE THREAD

**Issue by w1ll1am23** [dahlb/hatch_rest_api#16]
**Describe the bug**
Entities in Home Assistant didn't report unavailable but no interactions worked. Wasn't running debug logs :(

**To Reproduce**
Unknown. Maybe my token expired?

**Expected behavior**
Devices continue to work without needing a HA reboot. 

**Screenshots**
None

**Additional context**
Also noticed the wifi sensor stated disconnected so some sensors got created but some of the entities failed to function specifically the media player. 

Did look at full log but noticed this. 

```
Logger: homeassistant.components.media_player
Source: custom_components/ha_hatch/riot_media_entity.py:48
Integration: Media player (documentation, issues)
First occurred: January 22, 2023 at 9:04:49 PM (4 occurrences)
Last logged: January 22, 2023 at 9:09:10 PM

Error adding entities for domain media_player with platform ha_hatch
Error while setting up ha_hatch platform for media_player
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 438, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 709, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 803, in add_to_platform_finish
    await self.async_added_to_hass()
  File "/config/custom_components/ha_hatch/rest_entity.py", line 52, in async_added_to_hass
    self._update_local_state()
  File "/config/custom_components/ha_hatch/riot_media_entity.py", line 48, in _update_local_state
    _LOGGER.debug(f"updating state:{self.rest_device}")
  File "/usr/local/lib/python3.10/site-packages/hatch_rest_api/riot.py", line 120, in __str__
    return f"{self.__repr__()}"
  File "/usr/local/lib/python3.10/site-packages/hatch_rest_api/riot.py", line 113, in __repr__
    "is_clock_on": self.is_clock_on,
  File "/usr/local/lib/python3.10/site-packages/hatch_rest_api/riot.py", line 136, in is_clock_on
    return self.flags & RIOT_FLAGS_CLOCK_ON
TypeError: unsupported operand type(s) for &: 'NoneType' and 'int'

```

**Comment by dahlb** [comment]
not sure if this solves all of what you are experiencing but https://github.com/dahlb/hatch_rest_api/commit/3ad05efa4524f7ac6a402e10d054f752d9e5d92f should handle what's in the logs which is caused by the mqtt partial updates nature where some attributes are not initialized at all times

**Comment by dahlb** [comment]
the offline issue might have been related to https://github.com/dahlb/ha_hatch/issues/10

**Comment by w1ll1am23** [comment]
You're correct same issue today and I see the issue reported in that you linked to and I'm not seeing the same error about the flags.
